---
version: "2"

services:
  aws-cli:
    image: governmentpaas/awscli:latest
    volumes:
      - ./data/:/data/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  db:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - ./data/psql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: siis
      POSTGRES_PASSWORD: siis
    ports:
      - "5432:5432"
