---
version: "2"

services:
  aws-cli:
    image: governmentpaas/awscli:latest
    volumes:
      - ./data/:/data/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  db:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - ./data/psql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: siis
      POSTGRES_PASSWORD: siis
    ports:
      - "5432:5432"

  geoserver:
    image: docker-registry.data.bas.ac.uk/magic/siis/geoserver:latest
    build: ./geoserver
    volumes:
      - "./data/geoserver_extensions:/var/local/geoserver-exts/"
      - "./data/geoserver:/var/local/geoserver"
      - "./data/raw:/data"
    environment:
      JAVA_OPTS: -Dservice_pg_user=siis -Dservice_pg_pass=siis -Dservice_pg_host=db -Dservice_pg_port=5432 -Dservice_pg_db=siis
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    image: docker-registry.data.bas.ac.uk/magic/siis/api:latest
    build: ./api
    command: python api/api.py
    volumes:
      - ./api/api:/usr/src/app/api/
    environment:
      SERVICE_PG_CONN: "postgresql://siis:siis@db:5432/siis"
    ports:
      - "9001:5000"

  api-kv:
    image: docker-registry.data.bas.ac.uk/magic/siis/api-kv:latest
    build: ./api-kv
    command: flask run --host 0.0.0.0 --port 9002
    ports:
      - "9002:9002"
    depends_on:
      - db

  app:
    image: docker-registry.data.bas.ac.uk/magic/siis/app:latest
    build: ./app
    command: "yarn dev"
    volumes:
      - ./app/assets/:/usr/src/app/assets/
      - ./app/components/:/usr/src/app/components/
      - ./app/dist/:/usr/src/app/dist/
      - ./app/index.js/:/usr/src/app/index.js
      - ./app/index.html/:/usr/src/app/index.html
    environment:
      HOST: 0.0.0.0
      PORT: 9000
    ports:
      - "9000:9000"
    depends_on:
      - api
      - api-kv
      - geoserver
